# what is array?
- array ka istamal data ko index ki base pr store krnay kai liyai istamal hota is ki three type hai,faster than list,manage cploex data as compare list 
- one dimension array ("data ko single side pr represent krta hai ")
- two dimension array("two side mai data ko represent kiya jata hai xaxsis,or yaxsis pr ")

# what is an vector?
- same as one dimension array.
matrix?
- stored data in rows and columns form

# 1-D array

In [7]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [8]:
len(a)

3

In [9]:
a[2]

5

In [10]:
a[0:1]

array([5])

In [11]:
type(a)

numpy.ndarray

# 2-D array (use same commands)

In [13]:
import numpy as np
ll=np.array([[5,5,5],[5,5,5],[5,5,5]])
ll

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# how we can create a single dimension array
import numpy as np
a=np.array([5,5,5])
a

In [7]:
#how we can create a two dimension array 
import numpy as np
a=np.array([[5,5,5],[4,44,55],[77,44,44]])
a

array([[ 5,  5,  5],
       [ 4, 44, 55],
       [77, 44, 44]])

In [24]:
import numpy as np
zero=np.zeros(3)
zero

array([0., 0., 0.])

In [25]:
import numpy as np
one=np.ones(3)
one

array([1., 1., 1.])

In [26]:
import numpy as np
empty=np.empty(3)
empty

array([1., 1., 1.])

In [34]:
#print with arrange 
import numpy as np
q=np.arange(5)
q


array([0, 1, 2, 3, 4])

In [39]:
#print with  specific arange arrange 
import numpy as np
w=np.arange(0,20)
w


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
#continue
#print with  specific arange arrange 
import numpy as np
e=np.arange(2,50,5)
e

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [43]:
#linerly space array
#print with  specific arange arrange 
import numpy as np
r=np.linspace(2,50,num=1100)
r

array([ 2.        ,  2.04367607,  2.08735214, ..., 49.91264786,
       49.95632393, 50.        ])

In [48]:
#print with  specific arange arrange 
import numpy as np
p=np.ones(5,dtype=np.float32)
p

array([1., 1., 1., 1., 1.], dtype=float32)

In [51]:
import numpy as np
qp=np.zeros(5,dtype=np.int16)
qp

array([0, 0, 0, 0, 0], dtype=int16)

# 2D arrray

In [1]:
import numpy as np
qa=np.ones((2,3))
qa

array([[1., 1., 1.],
       [1., 1., 1.]])

In [2]:

np.zeros((5,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.empty((3,4))
#karbar (not satisfied by me )

array([[6.23042070e-307, 3.33776697e-307, 9.79054228e-307,
        9.34598926e-307],
       [1.11258854e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.37961302e-306,
        1.37954579e-306]])