# numpy practice section

In [1]:
import numpy as np


# creating an array using numpy

In [2]:
food=np.array(["pakoray","samosay","raita"])
food

array(['pakoray', 'samosay', 'raita'], dtype='<U7')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[2]

5

In [8]:
food[0]

'pakoray'

In [9]:
price.mean()

5.0

# different method of array

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,30)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# interval

In [15]:
np.arange(2,31,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30])

In [16]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# line space(provide same ans after taking interval or plus,minus )

In [17]:
np.linspace(2,1000,num=7)

array([   2.        ,  168.33333333,  334.66666667,  501.        ,
        667.33333333,  833.66666667, 1000.        ])

# specify the data type

In [18]:
np.zeros(50,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
np.empty(50,dtype=np.float64)

array([ 1.11836315e-311,  1.11838302e-311,  1.43085760e-258,
       -8.43041559e-201,  1.25162453e-308,  4.98900982e-273,
        2.32902545e-320,  5.76061555e-220,  0.00000000e+000,
       -2.30115195e-186, -1.55691449e-181,  1.05455513e+060,
        1.25990589e-300,  0.00000000e+000,  1.56687421e-305,
        5.53682373e-317,  6.02696856e-302,  2.86744456e-291,
        3.71217721e-309,  8.96902931e-312,  2.10966031e-321,
       -1.84022800e-157,  1.57695888e-296,  3.62861280e-312,
       -4.86894341e-095, -3.19163853e-090,  1.05819621e-300,
        1.38258698e-316, -5.29690186e-143,  1.92246382e-305,
        0.00000000e+000,  2.40761655e-301, -2.24532119e-080,
        9.06092203e-312, -1.14298739e-099,  3.52263885e-312,
        8.44852254e-322, -1.49094609e-128,  1.05455515e+060,
        1.25990589e-300,  0.00000000e+000,  1.56687425e-305,
        5.53682373e-317, -1.18280255e-099,  3.75563560e-309,
        8.96969243e-312,  2.10966031e-321,  2.40989507e-301,
        3.62861280e-312,

# Array functions

In [20]:
import numpy as np
l=np.array([10,12,15,2,4,6,100,10.3,2.3,55,5.0])
l

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. ,  10.3,   2.3,
        55. ,   5. ])

# sorting

In [21]:
l.sort()
l

array([  2. ,   2.3,   4. ,   5. ,   6. ,  10. ,  10.3,  12. ,  15. ,
        55. , 100. ])

In [22]:
b=np.array([33,44,5.5,55,77])
b

array([33. , 44. ,  5.5, 55. , 77. ])

# concatination(addition)

In [23]:
c=np.concatenate((l,b))
c

array([  2. ,   2.3,   4. ,   5. ,   6. ,  10. ,  10.3,  12. ,  15. ,
        55. , 100. ,  33. ,  44. ,   5.5,  55. ,  77. ])

In [24]:
c.sort()
c

array([  2. ,   2.3,   4. ,   5. ,   5.5,   6. ,  10. ,  10.3,  12. ,
        15. ,  33. ,  44. ,  55. ,  55. ,  77. , 100. ])

In [25]:
import numpy as np
ab=np.array([2,3,4])
ab

array([2, 3, 4])

In [26]:
g=np . array([4,5,4])
g

array([4, 5, 4])

In [27]:
np.concatenate((ab,g))


array([2, 3, 4, 4, 5, 4])

# two dimension (concatinations )

In [28]:
import numpy as np
a=np . array([[2,3,4],[44,5,44]])
a

array([[ 2,  3,  4],
       [44,  5, 44]])

In [29]:
import numpy as np
al=np . array([[2,5,4],[45,55,44]])
al

array([[ 2,  5,  4],
       [45, 55, 44]])

In [30]:
zy=np.concatenate((a,al))
zy

array([[ 2,  3,  4],
       [44,  5, 44],
       [ 2,  5,  4],
       [45, 55, 44]])

# how we can take concatination of two differnet dimension pairs (assinment)

In [31]:
np.concatenate((a,al),axis=1)

array([[ 2,  3,  4,  2,  5,  4],
       [44,  5, 44, 45, 55, 44]])

In [32]:
import numpy as np
lp=np.array([10,12,15])
lp

array([10, 12, 15])

In [33]:
import numpy as np
ld=np.array([[10,12,15],[5,77,88]])
ld

array([[10, 12, 15],
       [ 5, 77, 88]])

In [34]:
np.vstack((lp,ld))


array([[10, 12, 15],
       [10, 12, 15],
       [ 5, 77, 88]])

# stack

In [35]:
import numpy as np
lp=np.array([[10,12,15],[4,5,6]])
lp

array([[10, 12, 15],
       [ 4,  5,  6]])

In [36]:
import numpy as np
lpp=np.array([[10,12,15],[55,66,77]])
lpp

array([[10, 12, 15],
       [55, 66, 77]])

In [37]:
pl=np.concatenate((lp,lpp),axis=0)
pl

array([[10, 12, 15],
       [ 4,  5,  6],
       [10, 12, 15],
       [55, 66, 77]])

In [38]:
import numpy as np
lp=np.array([[10,12,15],[4,5,6]])
lp

array([[10, 12, 15],
       [ 4,  5,  6]])

In [39]:
import numpy as np
lpp=np.array([[10,12,15],[55,66,77]])
lpp

array([[10, 12, 15],
       [55, 66, 77]])

In [40]:
pl=np.concatenate((lp,lpp),axis=1)
pl

array([[10, 12, 15, 10, 12, 15],
       [ 4,  5,  6, 55, 66, 77]])

# 3D array

In [41]:
import numpy as np
al=np .array([[[2,7,7,8],
               [3,4,5,0]],
                        [[2,7,7,5],[3,4,5,2]],
                                   [[2,7,7,6],[3,4,5,9]]])
al

array([[[2, 7, 7, 8],
        [3, 4, 5, 0]],

       [[2, 7, 7, 5],
        [3, 4, 5, 2]],

       [[2, 7, 7, 6],
        [3, 4, 5, 9]]])

# how we can finf dimension

In [42]:
al.ndim

3

In [43]:
b=np.array([[5,6,7],[7,8,9]])
b

array([[5, 6, 7],
       [7, 8, 9]])

In [44]:
b.ndim

2

In [45]:
#size
b.size

6

In [46]:
#shape
al.shape

(3, 2, 4)

In [49]:
ll=np.arange(9)
ll

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
#reshape
ll.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



# 1D array to 2d array convertion


In [53]:
lm=np.array([1,2,3,45,6,7,7,])
lm

array([ 1,  2,  3, 45,  6,  7,  7])

In [55]:
lm.shape

(7,)

In [56]:
#row wise convertion
ln=lm[np.newaxis,:]
ln

array([[ 1,  2,  3, 45,  6,  7,  7]])

In [57]:
#colomnwise cinvertion
ln=lm[:,np.newaxis]
ln

array([[ 1],
       [ 2],
       [ 3],
       [45],
       [ 6],
       [ 7],
       [ 7]])

In [58]:
ln.shape

(7, 1)

# slicing/indexing 

In [60]:
ln

array([[ 1],
       [ 2],
       [ 3],
       [45],
       [ 6],
       [ 7],
       [ 7]])

In [61]:
ln[0:3]

array([[1],
       [2],
       [3]])

In [62]:
a

array([[ 2,  3,  4],
       [44,  5, 44]])

In [63]:
a*4

array([[  8,  12,  16],
       [176,  20, 176]])

In [64]:
a+3

array([[ 5,  6,  7],
       [47,  8, 47]])

In [66]:
#sum
ln.sum()

71

In [69]:
#mean
ln.mean()

10.142857142857142

In [4]:
# reversing an array 
import numpy as np
h=np.array([1,2,3,5,7,6])
h

array([1, 2, 3, 5, 7, 6])

In [5]:
np.flip(h)


array([6, 7, 5, 3, 2, 1])